spring:
  application:
    name: ms-account
  profiles:
    active:
      - dev #(2)
  config:
    import: optional:configserver:http://config-server:9010
  cloud:
    config:
      profile: dev

backend:
  #service:
    #url: http://localhost:8082/dummy-client2/saludo
  eureka:
    customer:
      get-by-id: http://server-gateway/customer/{id}